language: perl
perl:
  - "5.14"
  - "5.16"
before_install:
  - cpanm Carton
  - carton install
script:
  - carton exec -- prove -vr -Ilib t/
notifications:
  emails:
    - addsict@gmail.com
  on_success: always
  on_failure: always
